### ISSUE TITLE
compile issue with some notebooks

### ISSUE THREAD

**Issue by petravanhoudt** [OSIPI/DCE-DSC-MRI_TestResults#1]
Hi @notZaki, For some notebooks, e.g. VariableFlipAngle and SItoC there is an issue with the equations in the background section. On the website it looks like some text is within the equation, but in the notebook itself it looks fine. Any idea how this happens?

![image](https://user-images.githubusercontent.com/1290651/161087626-d17551ab-32bc-400e-b405-2daf02842f8e.png)

**Comment by notZaki** [comment]
@petravanhoudt Perhaps try adding an empty line before and after the equation block so that it looks something like:

```
text text text

$$
\equations
$$

more text text
```

**Comment by petravanhoudt** [comment]
thanks this solved it!
